services:
  - type: web
    name: haramaya-house-prediction
    env: python
    region: oregon
    plan: free
    buildCommand: cd haramaya_house_prediction && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: cd haramaya_house_prediction && gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        value: django-insecure-haramaya-house-prediction-render-deployment-2025
